import type { ItemsCatalog } from './types';

export const INITIAL_ITEMS_CATALOG = {
  items: [
    {
      id: 'fallen-branch',
      name: 'Graveto',
      description: 'Galho caído, útil para fogueira ou ferramenta improvisada.',
      kind: 'material',
      stackLimit: 99,
      tags: ['wood'],
    },
    {
      id: 'raw-water',
      name: 'Água bruta',
      description: 'Água coletada direto da nascente.',
      kind: 'consumable',
      stackLimit: 20,
      tags: ['drink'],
      use: { type: 'need.restore', need: 'sede', amount: 45 },
    },
    {
      id: 'agua-limpa',
      name: 'Água limpa',
      description: 'Água segura para beber.',
      kind: 'consumable',
      stackLimit: 20,
      tags: ['drink'],
      use: { type: 'need.restore', need: 'sede', amount: 45 },
    },
    {
      id: 'raw-horned-rabbit-meat',
      name: 'Carne crua de coelho chifrudo',
      description: 'Carne crua que precisa ser cozida.',
      kind: 'material',
      stackLimit: 20,
      tags: ['food', 'raw'],
    },
    {
      id: 'cooked-horned-rabbit-meat',
      name: 'Carne cozida de coelho chifrudo',
      description: 'Refeição simples que reduz a fome.',
      kind: 'consumable',
      stackLimit: 10,
      tags: ['food'],
      use: { type: 'need.restore', need: 'fome', amount: 36 },
    },
    {
      id: 'fruto-desconhecido',
      name: 'Fruto desconhecido',
      description: 'Um fruto encontrado depois do despertar.',
      kind: 'consumable',
      stackLimit: 20,
      tags: ['food'],
      use: { type: 'need.restore', need: 'fome', amount: 12 },
    },
    {
      id: 'horned-rabbit-hide',
      name: 'Couro de coelho chifrudo',
      description: 'Pele resistente, matéria-prima para ataduras.',
      kind: 'material',
      stackLimit: 20,
      tags: ['hide'],
    },
    {
      id: 'horned-rabbit-horn',
      name: 'Chifre de coelho chifrudo',
      description: 'Chifre curto e sólido.',
      kind: 'material',
      stackLimit: 20,
      tags: ['trophy'],
    },
    {
      id: 'horned-rabbit-bones',
      name: 'Ossos de coelho chifrudo',
      description: 'Ossos leves para uma ferramenta improvisada.',
      kind: 'material',
      stackLimit: 20,
      tags: ['bone'],
    },
    {
      id: 'galho-resistente',
      name: 'Galho resistente',
      description: 'Um galho mais firme que os gravetos comuns.',
      kind: 'material',
      stackLimit: 20,
      tags: ['wood'],
    },
    {
      id: 'predator-fang',
      name: 'Presa do predador',
      description: 'Uma presa arrancada do Predador Arisco.',
      kind: 'material',
      stackLimit: 10,
      tags: ['trophy'],
    },
    {
      id: 'improvised-tool',
      name: 'Ferramenta improvisada',
      description: 'Uma arma tosca de graveto e osso. Aumenta o dano dos golpes.',
      kind: 'equipment',
      stackLimit: 1,
      tags: ['weapon'],
      slot: 'main-hand',
      grants: [{ type: 'combat.value.modify', target: 'damage', amount: 2 }],
    },
    {
      id: 'improvised-salve',
      name: 'Unguento improvisado',
      description: 'Atadura preparada com couro. Recupera vitalidade no combate.',
      kind: 'consumable',
      stackLimit: 5,
      tags: ['medicine'],
      use: { type: 'combat.heal', amount: 8 },
    },
  ],
} as const satisfies ItemsCatalog;
