import type { StoryEvent } from '../../core/events';
import {
  ABILITY_EMPATHY,
  ABILITY_PERCEPTION,
  ABILITY_RESILIENCE,
  FLAG_ABILITY_EMPATHY,
  FLAG_ABILITY_PERCEPTION,
  FLAG_ABILITY_RESILIENCE,
  FLAG_CAMPED_ALONE,
  FLAG_CAMPED_TOGETHER,
  FLAG_DANGER_CONFRONTED,
  FLAG_DANGER_FLED,
  FLAG_DANGER_HIDDEN,
  FLAG_KEPT_RESOURCE,
  FLAG_REPAIRED,
  FLAG_SHARED_RESOURCE,
  FLAG_SHARED_WATER,
  FLAG_SOUGHT_LOCATION,
  FLAG_SOUGHT_SHELTER,
  FLAG_SOUGHT_WATER,
  ITEM_BRANCH,
  ITEM_FRUIT,
  ITEM_WATER,
  NPC_MIRA,
  TO_DANGER,
  TO_DUSK,
} from './ids';

export const events: StoryEvent[] = [
  {
    id: 'awakening',
    title: 'Despertar',
    body: 'Você abre os olhos sobre um chão que nunca existiu. A terra é fria, irregular, e o céu parece grande demais.\n\nNão há rua, muro, cama ou voz familiar. O nome {{nomeCompleto}} ainda cabe em você, mas o resto da vida ficou do outro lado de algo que as pessoas vão chamar de Reset.\n\nVocê está só. Sem pais, sem aliados, sem objeto algum. A maioridade chegou ontem. O mundo, hoje.',
    image: { kind: 'scene', label: 'Despertar após o Reset' },
    choices: [
      {
        id: 'awake-calm',
        label: 'Levantar com calma e observar',
        hint: 'A cautela aumenta. A energia cai pouco.',
        notable: true,
        effects: [
          { type: 'attribute.change', attribute: 'cautela', amount: 8 },
          { type: 'attribute.change', attribute: 'energia', amount: -6 },
          { type: 'world.period', period: 'manha' },
        ],
        transition: { type: 'event', eventId: 'system-awakens' },
      },
      {
        id: 'awake-quick',
        label: 'Levantar depressa, pronto para correr',
        hint: 'Você gasta energia e se machuca no terreno novo.',
        effects: [
          { type: 'attribute.change', attribute: 'energia', amount: -14 },
          { type: 'attribute.change', attribute: 'saude', amount: -6 },
          { type: 'world.period', period: 'manha' },
        ],
        transition: { type: 'event', eventId: 'system-awakens' },
      },
    ],
  },
  {
    id: 'system-awakens',
    title: 'O Sistema',
    body: 'Uma superfície translúcida se forma no ar, a um palmo dos olhos. Não é um aparelho. Não pesa. Ainda assim, você lê:\n\nUsuário reconhecido: {{nomeCompleto}}.\nSistema inicializado.\nCapacidade inicial disponível.\n\nTodo mundo tem isso agora. Não é um chamado exclusivo. É uma regra nova, tão silenciosa quanto o desaparecimento das cidades.',
    image: { kind: 'scene', label: 'Interface do Sistema' },
    choices: [
      {
        id: 'system-touch',
        label: 'Tocar o painel e aceitar a leitura',
        effects: [
          { type: 'flag.set', flag: 'system.acknowledged', value: true },
        ],
        transition: { type: 'event', eventId: 'choose-ability' },
      },
      {
        id: 'system-watch',
        label: 'Observar à distância, sem tocar',
        hint: 'A cautela aumenta.',
        effects: [
          { type: 'attribute.change', attribute: 'cautela', amount: 6 },
          { type: 'flag.set', flag: 'system.observed', value: true },
        ],
        transition: { type: 'event', eventId: 'choose-ability' },
      },
    ],
  },
  {
    id: 'choose-ability',
    title: 'Capacidade inicial',
    body: 'O Sistema não escolhe por você. Três caminhos se abrem, cada um com uma vantagem clara. Só um cabe neste primeiro dia.\n\nO resto, se existir, virá depois — das decisões, não de um destino escrito.',
    image: { kind: 'scene', label: 'Escolha de capacidade' },
    choices: [
      {
        id: 'ability-perception',
        label: 'Olhar Atento',
        hint: 'Cautela +15. Você percebe ameaças antes delas chegarem.',
        notable: true,
        effects: [
          { type: 'progression.ability', abilityId: ABILITY_PERCEPTION },
          { type: 'flag.set', flag: FLAG_ABILITY_PERCEPTION, value: true },
          { type: 'attribute.change', attribute: 'cautela', amount: 15 },
        ],
        transition: { type: 'returnToExploration' },
      },
      {
        id: 'ability-resilience',
        label: 'Resiliência',
        hint: 'Saúde +15 e energia +10. O corpo aguenta melhor o terreno.',
        notable: true,
        effects: [
          { type: 'progression.ability', abilityId: ABILITY_RESILIENCE },
          { type: 'flag.set', flag: FLAG_ABILITY_RESILIENCE, value: true },
          { type: 'attribute.change', attribute: 'saude', amount: 15 },
          { type: 'attribute.change', attribute: 'energia', amount: 10 },
        ],
        transition: { type: 'returnToExploration' },
      },
      {
        id: 'ability-empathy',
        label: 'Voz Calma',
        hint: 'Humanidade +15. Outras pessoas tendem a confiar mais depressa.',
        notable: true,
        effects: [
          { type: 'progression.ability', abilityId: ABILITY_EMPATHY },
          { type: 'flag.set', flag: FLAG_ABILITY_EMPATHY, value: true },
          { type: 'attribute.change', attribute: 'humanidade', amount: 15 },
        ],
        transition: { type: 'returnToExploration' },
      },
    ],
  },
  {
    id: 'first-priority',
    title: 'O que vem primeiro',
    canStartSession: true,
    body: 'A fome já cobra. A garganta pede água. O vento atravessa o vale sem nenhum teto para parar.\n\nAo longe, uma linha de pedras. À direita, um recorte de vegetação baixa. À esquerda, um morro de onde talvez se veja o tamanho disto.\n\nNão dá para fazer as três coisas agora.',
    image: { kind: 'scene', label: 'Vale recém-formado' },
    choices: [
      {
        id: 'seek-water',
        label: 'Procurar água',
        hint: 'Você encontra água limpa. A fome alivia um pouco.',
        notable: true,
        effects: [
          { type: 'flag.set', flag: FLAG_SOUGHT_WATER, value: true },
          { type: 'inventory.add', itemId: ITEM_WATER, quantity: 1 },
          { type: 'attribute.change', attribute: 'fome', amount: -10 },
          { type: 'attribute.change', attribute: 'energia', amount: -10 },
          { type: 'world.period', period: 'meio-dia' },
        ],
        transition: TO_DANGER,
      },
      {
        id: 'seek-shelter',
        label: 'Procurar abrigo',
        hint: 'Menos gasto de energia. A cautela aumenta.',
        notable: true,
        effects: [
          { type: 'flag.set', flag: FLAG_SOUGHT_SHELTER, value: true },
          { type: 'attribute.change', attribute: 'energia', amount: -6 },
          { type: 'attribute.change', attribute: 'cautela', amount: 8 },
          { type: 'world.period', period: 'meio-dia' },
        ],
        transition: TO_DANGER,
      },
      {
        id: 'seek-location',
        label: 'Subir para se localizar',
        hint: 'Cansa mais. A cautela aumenta ao ver o tamanho do mundo.',
        notable: true,
        effects: [
          { type: 'flag.set', flag: FLAG_SOUGHT_LOCATION, value: true },
          { type: 'attribute.change', attribute: 'energia', amount: -16 },
          { type: 'attribute.change', attribute: 'cautela', amount: 12 },
          { type: 'attribute.change', attribute: 'fome', amount: 8 },
          { type: 'world.period', period: 'meio-dia' },
        ],
        transition: TO_DANGER,
      },
    ],
  },
  {
    id: 'danger-alert',
    title: 'A coisa entre as folhas',
    body: 'O Olhar Atento avisa antes do som. Algo grande demais para um animal conhecido desloca a vegetação a vinte passos.\n\nA criatura mistura osso claro e musgo úmido. Não pertence à memória de {{nome}}. Os olhos, se é que são olhos, procuram movimento.\n\nJunto às raízes, um fruto denso brilha como se tivesse sido esquecido ali de propósito.',
    image: { kind: 'scene', label: 'Criatura entre a vegetação' },
    conditions: [{ type: 'flag.is', flag: FLAG_ABILITY_PERCEPTION, value: true }],
    choices: [
      {
        id: 'alert-hide',
        label: 'Esconder-se e esperar',
        hint: 'Cautela aumenta. Você leva o fruto quando ela se afasta.',
        notable: true,
        effects: [
          { type: 'flag.set', flag: FLAG_DANGER_HIDDEN, value: true },
          { type: 'attribute.change', attribute: 'cautela', amount: 6 },
          { type: 'attribute.change', attribute: 'energia', amount: -6 },
          { type: 'inventory.add', itemId: ITEM_FRUIT, quantity: 1 },
          { type: 'world.period', period: 'tarde' },
        ],
        transition: { type: 'event', eventId: 'survivor-meet' },
      },
      {
        id: 'alert-leave',
        label: 'Afastar-se em silêncio, levando o fruto',
        effects: [
          { type: 'flag.set', flag: FLAG_DANGER_FLED, value: true },
          { type: 'attribute.change', attribute: 'energia', amount: -10 },
          { type: 'inventory.add', itemId: ITEM_FRUIT, quantity: 1 },
          { type: 'world.period', period: 'tarde' },
        ],
        transition: { type: 'event', eventId: 'survivor-meet' },
      },
      {
        id: 'alert-confront',
        label: 'Confrontar com vantagem de posição',
        hint: 'A saúde cai. Você ganha um galho resistente e o fruto.',
        notable: true,
        effects: [
          { type: 'flag.set', flag: FLAG_DANGER_CONFRONTED, value: true },
          { type: 'attribute.change', attribute: 'saude', amount: -10 },
          { type: 'attribute.change', attribute: 'energia', amount: -12 },
          { type: 'attribute.change', attribute: 'humanidade', amount: -4 },
          { type: 'inventory.add', itemId: ITEM_FRUIT, quantity: 1 },
          { type: 'inventory.add', itemId: ITEM_BRANCH, quantity: 1 },
          { type: 'world.period', period: 'tarde' },
        ],
        transition: { type: 'event', eventId: 'survivor-meet' },
      },
    ],
  },
  {
    id: 'danger-sudden',
    title: 'O ataque',
    body: 'O mato explode tarde demais. Uma criatura de osso e musgo atravessa o espaço onde {{nome}} acabou de pisar.\n\nNão há nome para aquilo. Há peso, cheiro de terra molhada e a certeza de que o Reset não deixou o mundo vazio.\n\nUm fruto denso rolou para perto quando ela avançou.',
    image: { kind: 'scene', label: 'Emboscada no mato' },
    choices: [
      {
        id: 'sudden-dodge',
        label: 'Rolar para o lado e fugir com o fruto',
        hint: 'Saúde e energia caem.',
        notable: true,
        effects: [
          { type: 'flag.set', flag: FLAG_DANGER_FLED, value: true },
          { type: 'attribute.change', attribute: 'saude', amount: -12 },
          { type: 'attribute.change', attribute: 'energia', amount: -14 },
          { type: 'inventory.add', itemId: ITEM_FRUIT, quantity: 1 },
          { type: 'world.period', period: 'tarde' },
        ],
        transition: { type: 'event', eventId: 'survivor-meet' },
      },
      {
        id: 'sudden-endure',
        label: 'Encostar o ombro e resistir o impacto',
        hint: 'A Resiliência reduz o dano. Você fica com um galho e o fruto.',
        notable: true,
        conditions: [{ type: 'flag.is', flag: FLAG_ABILITY_RESILIENCE, value: true }],
        effects: [
          { type: 'flag.set', flag: FLAG_DANGER_CONFRONTED, value: true },
          { type: 'attribute.change', attribute: 'saude', amount: -8 },
          { type: 'attribute.change', attribute: 'energia', amount: -10 },
          { type: 'inventory.add', itemId: ITEM_FRUIT, quantity: 1 },
          { type: 'inventory.add', itemId: ITEM_BRANCH, quantity: 1 },
          { type: 'world.period', period: 'tarde' },
        ],
        transition: { type: 'event', eventId: 'survivor-meet' },
      },
      {
        id: 'sudden-fight',
        label: 'Enfrentar no imediato',
        hint: 'A saúde cai bastante. Você ganha um galho e o fruto.',
        notable: true,
        effects: [
          { type: 'flag.set', flag: FLAG_DANGER_CONFRONTED, value: true },
          { type: 'attribute.change', attribute: 'saude', amount: -22 },
          { type: 'attribute.change', attribute: 'energia', amount: -16 },
          { type: 'attribute.change', attribute: 'humanidade', amount: -6 },
          { type: 'inventory.add', itemId: ITEM_FRUIT, quantity: 1 },
          { type: 'inventory.add', itemId: ITEM_BRANCH, quantity: 1 },
          { type: 'world.period', period: 'tarde' },
        ],
        transition: { type: 'event', eventId: 'survivor-meet' },
      },
    ],
  },
  {
    id: 'survivor-meet',
    title: 'Outra voz',
    body: 'Depois da criatura, o vale parece menor. Então alguém tosse.\n\nÉ uma jovem, mais ou menos da sua idade, mãos vazias, ombros tensos. Ela não aponta arma porque não há arma. Só a distância entre dois desconhecidos.\n\n— Mira Vale — diz ela, como quem testa se o próprio nome ainda funciona. — Se você também acordou sozinho, não preciso inventar história.',
    image: { kind: 'scene', label: 'Encontro na clareira' },
    portrait: { kind: 'portrait', label: 'Sobrevivente desconhecida' },
    choices: [
      {
        id: 'meet-open',
        label: 'Aproximar-se com as mãos visíveis',
        hint: 'A confiança de Mira aumenta.',
        notable: true,
        effects: [
          { type: 'relationship.change', characterId: NPC_MIRA, amount: 12 },
          { type: 'attribute.change', attribute: 'humanidade', amount: 6 },
        ],
        transition: { type: 'event', eventId: 'moral-choice' },
      },
      {
        id: 'meet-calm',
        label: 'Falar baixo e esperar ela decidir a distância',
        hint: 'A Voz Calma rende mais confiança.',
        notable: true,
        conditions: [{ type: 'flag.is', flag: FLAG_ABILITY_EMPATHY, value: true }],
        effects: [
          { type: 'relationship.change', characterId: NPC_MIRA, amount: 20 },
          { type: 'attribute.change', attribute: 'humanidade', amount: 8 },
          { type: 'attribute.change', attribute: 'cautela', amount: 4 },
        ],
        transition: { type: 'event', eventId: 'moral-choice' },
      },
      {
        id: 'meet-distance',
        label: 'Falar à distância, sem se aproximar',
        effects: [
          { type: 'relationship.change', characterId: NPC_MIRA, amount: 6 },
          { type: 'attribute.change', attribute: 'cautela', amount: 6 },
        ],
        transition: { type: 'event', eventId: 'moral-choice' },
      },
      {
        id: 'meet-hide',
        label: 'Observar escondido antes de responder',
        hint: 'Menos humanidade. Ela percebe a hesitação.',
        effects: [
          { type: 'relationship.change', characterId: NPC_MIRA, amount: 2 },
          { type: 'attribute.change', attribute: 'cautela', amount: 8 },
          { type: 'attribute.change', attribute: 'humanidade', amount: -6 },
        ],
        transition: { type: 'event', eventId: 'moral-choice' },
      },
    ],
  },
  {
    id: 'moral-choice',
    title: 'O pouco que existe',
    body: 'Mira olha o fruto na sua mão com uma fome que ela tenta esconder. O dia ainda não acabou, e não há garantia de outro alimento.\n\n— Eu não vou pedir — diz ela. — Só... se a regra nova for cada um por si, eu preciso saber agora.\n\nO Sistema não sugere nada. A escolha é sua.',
    image: { kind: 'scene', label: 'Decisão sobre o alimento' },
    portrait: { kind: 'portrait', label: 'Mira Vale' },
    choices: [
      {
        id: 'share-fruit',
        label: 'Dividir o fruto com Mira',
        hint: 'Você perde o fruto. Confiança e humanidade aumentam.',
        notable: true,
        conditions: [{ type: 'inventory.has', itemId: ITEM_FRUIT, quantity: 1 }],
        effects: [
          { type: 'flag.set', flag: FLAG_SHARED_RESOURCE, value: true },
          { type: 'inventory.remove', itemId: ITEM_FRUIT, quantity: 1 },
          { type: 'relationship.change', characterId: NPC_MIRA, amount: 22 },
          { type: 'attribute.change', attribute: 'humanidade', amount: 12 },
          { type: 'attribute.change', attribute: 'fome', amount: -8 },
          { type: 'world.period', period: 'entardecer' },
        ],
        transition: TO_DUSK,
      },
      {
        id: 'share-all',
        label: 'Dividir o fruto e a água',
        hint: 'Exige água no inventário. A confiança sobe bastante.',
        notable: true,
        conditions: [
          { type: 'inventory.has', itemId: ITEM_WATER, quantity: 1 },
          { type: 'inventory.has', itemId: ITEM_FRUIT, quantity: 1 },
        ],
        effects: [
          { type: 'flag.set', flag: FLAG_SHARED_RESOURCE, value: true },
          { type: 'flag.set', flag: FLAG_SHARED_WATER, value: true },
          { type: 'inventory.remove', itemId: ITEM_FRUIT, quantity: 1 },
          { type: 'inventory.remove', itemId: ITEM_WATER, quantity: 1 },
          { type: 'relationship.change', characterId: NPC_MIRA, amount: 30 },
          { type: 'attribute.change', attribute: 'humanidade', amount: 16 },
          { type: 'attribute.change', attribute: 'fome', amount: -12 },
          { type: 'world.period', period: 'entardecer' },
        ],
        transition: TO_DUSK,
      },
      {
        id: 'keep-resource',
        label: 'Guardar o que você tem',
        hint: 'A confiança cai. Você mantém o alimento.',
        notable: true,
        effects: [
          { type: 'flag.set', flag: FLAG_KEPT_RESOURCE, value: true },
          { type: 'relationship.change', characterId: NPC_MIRA, amount: -12 },
          { type: 'attribute.change', attribute: 'humanidade', amount: -10 },
          { type: 'world.period', period: 'entardecer' },
        ],
        transition: TO_DUSK,
      },
    ],
  },
  {
    id: 'dusk-trusted',
    title: 'O fogo que ela aceita dividir',
    body: 'O entardecer desce mais rápido do que a memória de {{nome}} espera. Mira não fala do fruto outra vez. Só aponta um oco entre raízes, onde o vento quebra.\n\n— Você não precisava ter dividido — diz ela, já reunindo gravetos secos. — Por isso mesmo, o fogo pode ser dos dois. Se quiser.\n\nA primeira noite não vai ser confortável. Pode, no entanto, não ser solitária.',
    image: { kind: 'scene', label: 'Abrigo improvisado no entardecer' },
    portrait: { kind: 'portrait', label: 'Mira Vale' },
    conditions: [{ type: 'flag.is', flag: FLAG_SHARED_RESOURCE, value: true }],
    choices: [
      {
        id: 'accept-shelter',
        label: 'Aceitar o abrigo e o fogo',
        hint: 'Energia e saúde se recuperam um pouco.',
        notable: true,
        effects: [
          { type: 'flag.set', flag: FLAG_CAMPED_TOGETHER, value: true },
          { type: 'attribute.change', attribute: 'energia', amount: 18 },
          { type: 'attribute.change', attribute: 'saude', amount: 8 },
          { type: 'attribute.change', attribute: 'fome', amount: -6 },
          { type: 'relationship.change', characterId: NPC_MIRA, amount: 8 },
          { type: 'progression.title', titleId: 'mao-partilhada' },
          { type: 'world.period', period: 'noite' },
        ],
        transition: { type: 'event', eventId: 'night-together' },
      },
      {
        id: 'decline-shelter',
        label: 'Agradecer e seguir sozinho',
        hint: 'A cautela aumenta. Você passa a noite sem companhia.',
        notable: true,
        effects: [
          { type: 'flag.set', flag: FLAG_CAMPED_ALONE, value: true },
          { type: 'attribute.change', attribute: 'cautela', amount: 8 },
          { type: 'attribute.change', attribute: 'energia', amount: 6 },
          { type: 'relationship.change', characterId: NPC_MIRA, amount: -4 },
          { type: 'progression.title', titleId: 'caminho-solitario' },
          { type: 'world.period', period: 'noite' },
        ],
        transition: { type: 'event', eventId: 'night-alone' },
      },
    ],
  },
  {
    id: 'dusk-wary',
    title: 'A distância que ficou',
    body: 'Mira não discute o alimento. Guarda as mãos junto ao corpo e aponta um vale mais baixo, onde o vento bate menos.\n\n— Cada um por si, então — diz ela. — Eu não vou te seguir. Também não vou fingir que isso aqui é um começo.\n\nAinda assim, ela não some de imediato. O primeiro dia está acabando para os dois.',
    image: { kind: 'scene', label: 'Separação no entardecer' },
    portrait: { kind: 'portrait', label: 'Mira Vale' },
    choices: [
      {
        id: 'repair-offer',
        label: 'Pedir desculpas e oferecer a água agora',
        hint: 'Exige água. Pode reabrir o caminho do abrigo.',
        notable: true,
        conditions: [{ type: 'inventory.has', itemId: ITEM_WATER, quantity: 1 }],
        effects: [
          { type: 'flag.set', flag: FLAG_REPAIRED, value: true },
          { type: 'flag.set', flag: FLAG_CAMPED_TOGETHER, value: true },
          { type: 'inventory.remove', itemId: ITEM_WATER, quantity: 1 },
          { type: 'relationship.change', characterId: NPC_MIRA, amount: 14 },
          { type: 'attribute.change', attribute: 'humanidade', amount: 8 },
          { type: 'attribute.change', attribute: 'energia', amount: 12 },
          { type: 'progression.title', titleId: 'gesto-tardio' },
          { type: 'world.period', period: 'noite' },
        ],
        transition: { type: 'event', eventId: 'night-together' },
      },
      {
        id: 'stay-apart',
        label: 'Permanecer no mesmo vale, à distância',
        notable: true,
        conditions: [{ type: 'inventory.has', itemId: ITEM_FRUIT, quantity: 1 }],
        effects: [
          { type: 'flag.set', flag: FLAG_CAMPED_ALONE, value: true },
          { type: 'attribute.change', attribute: 'energia', amount: 8 },
          { type: 'attribute.change', attribute: 'cautela', amount: 6 },
          { type: 'attribute.change', attribute: 'fome', amount: -10 },
          { type: 'inventory.remove', itemId: ITEM_FRUIT, quantity: 1 },
          { type: 'progression.title', titleId: 'caminho-solitario' },
          { type: 'world.period', period: 'noite' },
        ],
        transition: { type: 'event', eventId: 'night-alone' },
      },
      {
        id: 'walk-away',
        label: 'Afastar-se e passar a noite sozinho',
        notable: true,
        conditions: [{ type: 'inventory.has', itemId: ITEM_FRUIT, quantity: 1 }],
        effects: [
          { type: 'flag.set', flag: FLAG_CAMPED_ALONE, value: true },
          { type: 'attribute.change', attribute: 'cautela', amount: 10 },
          { type: 'attribute.change', attribute: 'energia', amount: 4 },
          { type: 'attribute.change', attribute: 'fome', amount: -10 },
          { type: 'inventory.remove', itemId: ITEM_FRUIT, quantity: 1 },
          { type: 'progression.title', titleId: 'caminho-solitario' },
          { type: 'world.period', period: 'noite' },
        ],
        transition: { type: 'event', eventId: 'night-alone' },
      },
    ],
  },
  {
    id: 'night-together',
    title: 'A primeira noite',
    body: 'O fogo é pequeno e o sono não é profundo. Ainda assim, há outra respiração no escuro e um acordo não dito: ninguém some enquanto o outro estiver de guarda.\n\nO Sistema registra o dia sem fanfarra. Não entrega um destino. Só confirma que {{nomeCompleto}} ainda está aqui.\n\nAmanhã o mundo continua maior do que deveria. Hoje, isso basta.',
    image: { kind: 'scene', label: 'Noite compartilhada' },
    isEnding: true,
    choices: [
      {
        id: 'together-summary',
        label: 'Ver o que o primeiro dia deixou',
        effects: [{ type: 'game.complete' }],
        transition: { type: 'complete' },
      },
    ],
  },
  {
    id: 'night-alone',
    title: 'A primeira noite',
    body: 'O escuro chega inteiro. Sem parede, sem voz, sem certeza de que o vale ainda será o mesmo ao amanhecer.\n\nVocê ouve coisas que a memória não classifica. O Sistema permanece à margem da visão, silencioso, como se também estivesse aprendendo a esperar.\n\n{{nomeCompleto}} atravessa o primeiro dia. Sozinho, por enquanto.',
    image: { kind: 'scene', label: 'Noite solitária' },
    isEnding: true,
    choices: [
      {
        id: 'alone-summary',
        label: 'Ver o que o primeiro dia deixou',
        effects: [{ type: 'game.complete' }],
        transition: { type: 'complete' },
      },
    ],
  },
];
